### ISSUE TITLE
Diff con data.ingv.it: numero totale di dati disponibili

### ISSUE THREAD

**Issue by MarioLocati** [ingv-oe-dev/oedatarep-invenio-rdm#13]
data.ingv.it mostra il numero di dati (schede di metadati) disponibili

**Comment by fpistagna** [comment]
Dalla _home_ del portale dei dati aperti ([data.ingv.it](url)), questo dettaglio è visibile in un _box_ sulla _side_bar_ a destra:

<img width="352" height="641" alt="Image" src="https://github.com/user-attachments/assets/07a696eb-ff9f-462d-94b2-c79d0d15b6c2" />

In particolare nella box:

- il dettaglio del numero dei dataset totali
- i dettagli del numero dei dataset raggruppati per "classificazione".

Quest'ultimo dettaglio relativo alla "classificazione" è poi visibile anche nella pagine di dettaglio di ciascun dataset.

Questa informazione (Stringa testuale) non viene fornita durante l'operazione di creazione bozza e aggiunta metadati da Metadata Editor -> OEDataRep.

@MarioLocati E' possibile fornirla?
@mtorrisi sapresti suggerire un field dei metadati di InvenioRDM?

**Comment by mtorrisi** [comment]
> [@mtorrisi](https://github.com/mtorrisi) sapresti suggerire un field dei metadati di InvenioRDM?

Potremmo utilizzare il field `Subjects` dei metadati (https://inveniordm.docs.cern.ch/reference/metadata/#subjects-0-n)

**Comment by fpistagna** [comment]
> > [@mtorrisi](https://github.com/mtorrisi) sapresti suggerire un field dei metadati di InvenioRDM?
> 
> Potremmo utilizzare il field `Subjects` dei metadati (https://inveniordm.docs.cern.ch/reference/metadata/#subjects-0-n)

Adesso questo campo viene usato per le `keywords` ; 
In un processo automatizzato di `discovery` del campo di interesse (Classificazione) bisognerà poi capire come discriminare dalle altre `keywords`;

**Comment by MarioLocati** [comment]
No, il campo subject è dedicato appunto ai "subjects", metadato mappato nello schema DataCite.
Qui stiamo parlando invece di una classificazione definita dall'INGV, non si appoggia né a uno standard definito né è attualmente mappata nell schema DataCite.

Serve un campo custom, nel Registro si chiama "class", questi i valori al momento ammessi:
0. Non assegnata
1. Dati Vulcanologici
2. Dati Geochimici (analisi geochimiche di rocce, acque e gas)
3. Dati Geodetici
4. Dati Sismologici e Infrasonici (terrestri e marini)
5. Dati di campioni fisici (campioni e parametri fisici di rocce, minerali e materiali vari)
6. Dati di Geofisica atmosferica e Aeronomia
7. Dati Geologici (terrestri e marini)
8. Dati Geofisici terrestri (Geomagnetici, Geoelettrici, Elettro-Magnetici) e marini
9. Dati da Modelli Numerici
10. Dati di Telerilevamento
11. Dati Bibliografici

**Comment by fpistagna** [comment]
> questi i valori al momento ammessi: 
>     0. Non assegnata
> 
>     1. Dati Vulcanologici
> 
>     2. Dati Geochimici (analisi geochimiche di rocce, acque e gas)
> 
>     3. Dati Geodetici
> 
>     4. Dati Sismologici e Infrasonici (terrestri e marini)
> 
>     5. Dati di campioni fisici (campioni e parametri fisici di rocce, minerali e materiali vari)
> 
>     6. Dati di Geofisica atmosferica e Aeronomia
> 
>     7. Dati Geologici (terrestri e marini)
> 
>     8. Dati Geofisici terrestri (Geomagnetici, Geoelettrici, Elettro-Magnetici) e marini
> 
>     9. Dati da Modelli Numerici
> 
>     10. Dati di Telerilevamento
> 
>     11. Dati Bibliografici

Un vocabolario (formato .yaml) per la definizione di queste classificazioni di questo tipo, potrebbe rispecchiare la totalità dei casi (finora trattati) ? Durante la fase di creazione bozza (POST) il Metadata Editor dovrà soltanto referenziare l'id corrispondente per specificare il tipo di classificazione

```yaml
- id: "0"
  title:
    it: "Non assegnata"
    en: "Unassigned"
- id: "1"
  title:
    it: "Dati Vulcanologici"
    en: "Volcanological Data"
- id: "2"
  title:
    it: "Dati Geochimici (analisi geochimiche di rocce, acque e gas)"
    en: "Geochemical Data (geochemical analyses of rocks, waters, and gases)"
- id: "3"
  title:
    it: "Dati Geodetici"
    en: "Geodetic Data"
- id: "4"
  title:
    it: "Dati Sismologici e Infrasonici (terrestri e marini)"
    en: "Seismological and Infrasonic Data (terrestrial and marine)"
- id: "5"
  title:
    it: "Dati di campioni fisici (campioni e parametri fisici di rocce, minerali e materiali vari)"
    en: "Physical Sample Data (samples and physical parameters of rocks, minerals, and various materials)"
- id: "6"
  title:
    it: "Dati di Geofisica atmosferica e Aeronomia"
    en: "Atmospheric Geophysics and Aeronomy Data"
- id: "7"
  title:
    it: "Dati Geologici (terrestri e marini)"
    en: "Geological Data (terrestrial and marine)"
- id: "8"
  title:
    it: "Dati Geofisici terrestri (Geomagnetici, Geoelettrici, Elettro-Magnetici) e marini"
    en: "Terrestrial (Geomagnetic, Geoelectric, Electro-Magnetic) and Marine Geophysical Data"
- id: "9"
  title:
    it: "Dati da Modelli Numerici"
    en: "Numerical Model Data"
- id: "10"
  title:
    it: "Dati di Telerilevamento"
    en: "Remote Sensing Data"
- id: "11"
  title:
    it: "Dati Bibliografici"
    en: "Bibliographic Data"
```
